[package]
name = "area-axum"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = { version = "0.6.19" }
tokio = { version = "1.0", features = ["full"] }
area-db = { version = "0.0.*", path = "../../" }
serde = { version = "1.0.*" }
serde_json = "1.0.*"
